from .bases import bases_bp
from .cargo_config import cargo_config_bp
from .cargos import cargos_bp
from .centros_custo import centros_custo_bp
from .clientes import clientes_bp
from .colaboradores import colaboradores_bp
from .core_view import app_bp
from .cotacoes import cotacoes_bp
from .enderecos import enderecos_bp
from .estoque_categorias import categorias_bp
from .estoque_itens import itens_bp
from .estoque import estoque_bp
from .fornecedores import fornecedores_bp
from .notas import notas_bp
from .sub_centros_custo import sub_centros_custo_bp
from .tipos_documento import tipos_documento_bp